#!/usr/bin/env python3
"""80 comparison pages across AI, Marketing, Sales, Tools."""
from _build_comparisons import build_comparisons


def C(slug, a, b, topic, subtitle, tldr, matrix, pick_a, pick_b, verdict):
    return {'slug': slug, 'a': a, 'b': b, 'topic': topic, 'subtitle': subtitle,
            'tldr': tldr, 'matrix': matrix, 'pick_a': pick_a, 'pick_b': pick_b, 'verdict': verdict}


# Helper shortcuts
def ul(items):
    return "<ul>" + "".join(f"<li>{i}</li>" for i in items) + "</ul>"

def p(text):
    return f"<p>{text}</p>"


COMPARISONS = [
    # AI / LLMs
    C("claude-vs-gpt4", "Claude", "GPT-4", "AI Models",
      "Both are flagship LLMs. Different strengths on reasoning, coding, and tool use.",
      "Claude (Anthropic) and GPT-4 (OpenAI) are the two dominant frontier LLMs. They're close in capability; most practical advantages come down to specific workloads and ecosystem fit.",
      [
          ("Origin", "Anthropic", "OpenAI"),
          ("Pricing", "$3/$15 per M tokens (Sonnet)", "$5/$15 per M tokens (GPT-4o)"),
          ("Context window", "200K+", "128K (GPT-4o)"),
          ("Coding", "Strong, especially Claude Code", "Very strong"),
          ("Tool use", "Native, well-designed API", "Native, widely used"),
          ("Safety posture", "More cautious, refuses more", "Less cautious"),
          ("Best known for", "Long context, coding, writing", "Reasoning, breadth of integrations"),
      ],
      p("You prefer long context windows, better writing quality, or you're building with the Claude Agent SDK or Claude Code."),
      p("You want the broadest ecosystem (plugins, Assistants API, ChatGPT), or you've standardized on the OpenAI SDK."),
      p("For most production agent work in 2026, I reach for Claude first for coding and writing, GPT-4o for reasoning-heavy tasks, and route by task type.")),

    C("claude-vs-gemini", "Claude", "Gemini", "AI Models",
      "Anthropic vs Google. Different tradeoffs on context, cost, and integrations.",
      "Claude is the writing and coding specialist. Gemini wins on massive context (1M+ tokens) and Google ecosystem integrations.",
      [("Context", "200K", "1M+ (Gemini Pro)"),
       ("Integration", "Standalone API, MCP", "Google Workspace, search"),
       ("Price (flagship)", "$3-15/M tokens", "$1.25-5/M tokens"),
       ("Coding", "Strong", "Good"),
       ("Multimodal", "Good", "Best (native design)")],
      p("Writing, coding, reasoning depth."),
      p("Massive context, Google integrations, price sensitivity."),
      p("Claude for craft, Gemini for scale. For enterprise Google Workspace customers, Gemini's integration wins on workflow.")),

    C("gpt4-vs-gemini", "GPT-4", "Gemini", "AI Models",
      "Two flagship models with different strengths.",
      "GPT-4 has the broadest ecosystem. Gemini has the biggest context and Google integrations.",
      [("Ecosystem", "Largest (plugins, GPTs)", "Google suite"),
       ("Context", "128K", "1M+"),
       ("Cost", "Premium", "Competitive"),
       ("Reasoning", "Top-tier", "Strong")],
      p("Broad ecosystem access, familiar API, ChatGPT users."),
      p("Long documents, cost efficiency, Google Workspace."),
      p("Use GPT-4 when you need plugins/ecosystem, Gemini when you need 1M+ context or deep Google integrations.")),

    C("haiku-vs-4o-mini", "Claude Haiku", "GPT-4o-mini", "AI Models",
      "Small, fast, cheap models for high-volume use cases.",
      "Both are fast and cheap. Haiku is slightly more cautious; 4o-mini is slightly more flexible. Pick by workload.",
      [("Speed", "Very fast", "Very fast"),
       ("Cost", "$0.25/$1.25 per M", "$0.15/$0.60 per M"),
       ("Context", "200K", "128K")],
      p("When you need Anthropic's safety posture or are building in Claude ecosystem."),
      p("When cost is the top priority or you're on OpenAI."),
      p("Both are excellent for classification, extraction, routing. Pick by ecosystem.")),

    # Vector DBs
    C("pinecone-vs-weaviate", "Pinecone", "Weaviate", "Vector DBs",
      "Two of the most popular vector databases. Different posture on managed vs open-source.",
      "Pinecone is fully managed, serverless pricing, easiest to start. Weaviate is open-source with managed option, stronger hybrid search, richer filtering.",
      [("Hosted", "Managed only", "Self-hosted or managed"),
       ("Pricing", "Usage-based (serverless)", "Cheaper self-hosted"),
       ("Hybrid search", "Sparse + dense", "Native BM25 + dense"),
       ("Filtering", "Solid", "Excellent"),
       ("Scaling", "Easy", "Requires ops knowledge")],
      p("Starting fast, managed preference, simple multi-tenancy."),
      p("Self-hosting, advanced hybrid search, richer filtering needs."),
      p("Pinecone for quick starts. Weaviate when you need hybrid search and scale on your infrastructure.")),

    C("pinecone-vs-qdrant", "Pinecone", "Qdrant", "Vector DBs",
      "Managed leader vs open-source leader. Different cost curves.",
      "Pinecone is the easiest to get started with. Qdrant offers excellent open-source performance with strong filtering and quantization support.",
      [("Managed", "Pinecone cloud only", "Qdrant cloud or self"),
       ("Performance", "Strong", "Rust-based, extremely fast"),
       ("Quantization", "Supported", "Strong native (binary, scalar)"),
       ("Cost at scale", "Higher", "Lower (self-hosted)")],
      p("You want no-ops, and Pinecone's serverless pricing fits your volume."),
      p("You're scaling and want self-hosting, strong filtering, and aggressive quantization options."),
      p("Start with Pinecone; migrate to Qdrant self-hosted when scale or cost makes the migration worth it.")),

    C("weaviate-vs-qdrant", "Weaviate", "Qdrant", "Vector DBs",
      "Two strong open-source vector DBs with different design tradeoffs.",
      "Both are production-ready open source. Weaviate leans toward rich features and hybrid search; Qdrant leans toward raw performance and filtering.",
      [("Language", "Go", "Rust"),
       ("Hybrid search", "Native BM25", "Via sparse vectors"),
       ("Filtering", "Strong", "Excellent performance"),
       ("Modules", "Many built-in", "Lean core")],
      p("You want batteries-included (hybrid search, embeddings modules)."),
      p("You want max speed and tight filtering, will bring your own embedding pipeline."),
      p("Weaviate when you want an opinionated system. Qdrant when you want a performance primitive you build around.")),

    C("pgvector-vs-pinecone", "pgvector", "Pinecone", "Vector DBs",
      "Postgres extension vs dedicated vector DB.",
      "pgvector is free and integrates with your existing Postgres. Pinecone is purpose-built for vector search at scale. Choice depends on scale and simplicity priorities.",
      [("Cost", "Marginal (existing DB)", "Usage-based"),
       ("Scale", "Good to 1-10M vectors", "Billions"),
       ("Setup", "SQL, familiar", "New API"),
       ("Features", "Basic HNSW", "Rich (filtering, quantization)")],
      p("You already run Postgres, under 10M vectors, want simplicity."),
      p("Serious scale, want purpose-built features, accept managed cost."),
      p("pgvector until you outgrow it. Most teams never need to migrate.")),

    C("chroma-vs-pinecone", "Chroma", "Pinecone", "Vector DBs",
      "Embedded vs managed. Different use cases entirely.",
      "Chroma is great for local dev, prototyping, single-node deployments. Pinecone is a production managed service.",
      [("Hosting", "Embedded or self", "Managed only"),
       ("Scale", "Single node, ~millions", "Billions"),
       ("Use case", "Prototype, desktop apps", "Production at scale")],
      p("Prototyping, Notebook work, small deployments, local-first apps."),
      p("Production applications with real scale."),
      p("Chroma for exploration, Pinecone for shipping.")),

    C("milvus-vs-pinecone", "Milvus", "Pinecone", "Vector DBs",
      "Enterprise open-source vs managed leader.",
      "Milvus is built for enormous scale (billion+ vectors) but requires significant operational investment. Pinecone gives you scale without the ops.",
      [("Scale ceiling", "Billions+", "Billions+"),
       ("Ops burden", "High", "None"),
       ("Cost at scale", "Compute only", "Higher"),
       ("Learning curve", "Steep", "Gentle")],
      p("Extreme scale where ops cost is less than managed cost."),
      p("Managed simplicity, easier hiring."),
      p("Milvus when you have dedicated infra teams. Pinecone when you don't.")),

    # Embedding models
    C("openai-embed-vs-voyage", "OpenAI text-embedding-3", "Voyage-3", "Embeddings",
      "Both flagship embedding APIs. Different strengths.",
      "OpenAI's text-embedding-3 is the most widely used. Voyage consistently tops MTEB in specific domains (finance, law, code).",
      [("Price (large)", "$0.13/M tokens", "$0.18/M tokens"),
       ("Dimensions", "3072 (MRL)", "2048"),
       ("MTEB rank", "Strong", "Top tier"),
       ("Specialty", "General", "Domain specialist models")],
      p("General-purpose retrieval, cost-sensitive workloads, ecosystem fit."),
      p("Domain-specific workloads (finance, legal, code) or top-of-benchmark quality."),
      p("Start with OpenAI. Evaluate Voyage if your domain has a specialty model available.")),

    C("openai-embed-vs-cohere", "OpenAI text-embedding-3", "Cohere embed-v3", "Embeddings",
      "Two managed embedding APIs.",
      "Cohere is particularly strong for multilingual retrieval and has a well-paired reranker (Cohere Rerank).",
      [("Languages", "Good English + others", "Excellent multilingual"),
       ("Reranker pairing", "Via Anthropic/OpenAI", "Native Cohere Rerank"),
       ("Price", "$0.02-0.13/M", "~$0.10/M")],
      p("English-first, cost-sensitive, simple stack."),
      p("Multilingual retrieval or want to pair with Cohere Rerank."),
      p("OpenAI for most English workloads. Cohere for multilingual or when rerank is mandatory.")),

    C("bge-vs-nomic", "BGE-M3", "nomic-embed-v1.5", "Embeddings",
      "Two top open-source embedding models.",
      "BGE-M3 excels at multilingual and unified dense/sparse/colbert retrieval. Nomic is efficient, 8K context, strong on English.",
      [("Context", "8K", "8K"),
       ("Multilingual", "Excellent", "English-focused"),
       ("License", "Apache-2.0", "Apache-2.0"),
       ("Hybrid", "Unified dense/sparse/colbert", "Dense only")],
      p("Multilingual, want hybrid retrieval from one model."),
      p("English, want efficient deployment, simple integration."),
      p("BGE-M3 for breadth. Nomic for English production workloads with tight cost.")),

    # Email + outreach tools
    C("instantly-vs-smartlead", "Instantly", "Smartlead", "Cold Email",
      "Two of the most popular cold email tools in 2026.",
      "Both share similar feature sets: multi-inbox rotation, warming, unified inbox. Differences come down to UI preference and pricing at volume.",
      [("Built-in warming", "Yes, large network", "Yes, large network"),
       ("Multi-inbox", "Unlimited plans available", "Unlimited plans available"),
       ("Pricing tier", "$37-97/month", "$33-94/month"),
       ("Unified inbox", "Strong", "Strong"),
       ("Integrations", "Solid", "Solid")],
      p("Slightly larger community, more tutorials."),
      p("Slightly more affordable at top tier, similar features."),
      p("Either works. Pick based on UI preference after a demo of each.")),

    C("instantly-vs-lemlist", "Instantly", "Lemlist", "Cold Email",
      "Volume-focused vs personalization-focused.",
      "Instantly is optimized for volume cold outbound. Lemlist has stronger personalization features (images, video, LinkedIn integration) at higher price.",
      [("Focus", "Volume", "Personalization"),
       ("Image personalization", "Limited", "Strong"),
       ("LinkedIn automation", "Limited", "Native"),
       ("Pricing", "$37-97/month", "$59-135/month")],
      p("High-volume B2B outbound, simple personalization."),
      p("Personalization-heavy (images, creator videos, LinkedIn integration), smaller volume."),
      p("Instantly for scale, Lemlist for high-touch personalized outbound.")),

    C("salesloft-vs-outreach", "Salesloft", "Outreach", "Sales Engagement",
      "The two enterprise sales engagement platforms.",
      "Very similar feature sets. Both handle email, phone, LinkedIn, tasks, coaching. Choice usually comes down to sales team preference and integration fit.",
      [("Focus", "Sales engagement", "Sales engagement"),
       ("Email", "Strong", "Strong"),
       ("Phone", "Native", "Native"),
       ("AI coaching", "Built-in", "Built-in"),
       ("Price", "$125-165/user", "Comparable, quote-based")],
      p("UX preference, integrations with your stack."),
      p("UX preference, integrations with your stack."),
      p("These are interchangeable at a high level. Pick based on team trial.")),

    C("apollo-vs-zoominfo", "Apollo", "ZoomInfo", "B2B Data",
      "Two B2B contact databases with different price points and quality.",
      "Apollo is cheaper and includes a built-in sequencing tool. ZoomInfo has more accurate data, especially for senior contacts and phone numbers, at enterprise pricing.",
      [("Price", "$49-149/user", "Quote-based, usually $15K+/yr"),
       ("Data quality", "Solid", "Best in class for enterprise contacts"),
       ("Built-in outreach", "Yes", "Via Engage add-on"),
       ("International", "Good", "Strong (with global add-on)"),
       ("Phone numbers", "Variable", "Strong direct dials")],
      p("SMB/mid-market, budget-conscious, want all-in-one data + outreach."),
      p("Enterprise, need accurate direct dials, willing to pay for quality."),
      p("Apollo for most teams. ZoomInfo when enterprise contact accuracy justifies the price jump.")),

    C("apollo-vs-clay", "Apollo", "Clay", "B2B Data",
      "Contact database vs enrichment platform.",
      "Apollo is a contact database with built-in outreach. Clay is an orchestration layer that calls multiple data providers (including Apollo) plus custom enrichment.",
      [("Primary function", "Contact database", "Enrichment orchestration"),
       ("Data waterfalls", "No", "Yes (multi-provider)"),
       ("AI enrichment", "Limited", "Strong (custom prompts)"),
       ("Outreach", "Built-in", "Via push to sequencer")],
      p("Want simple contact source + outreach in one tool."),
      p("Want max coverage (waterfall across providers) and custom AI enrichment."),
      p("Most teams need both: Apollo as primary source, Clay to enrich lists with signals and AI-generated first lines.")),

    C("hubspot-vs-salesforce", "HubSpot", "Salesforce", "CRM",
      "SMB-friendly vs enterprise-grade CRM.",
      "HubSpot is easier to use, built-in marketing/sales/service modules. Salesforce is more customizable, enterprise-proven, more expensive.",
      [("Target", "SMB/mid-market", "Enterprise"),
       ("Learning curve", "Gentle", "Steep"),
       ("Customization", "Moderate", "Extreme"),
       ("Price", "$0-1200+/user", "$150-500+/user"),
       ("Ecosystem", "Growing", "Largest in B2B SaaS")],
      p("Smaller teams, want marketing+sales+service in one, budget sensitive."),
      p("Enterprise scale, need deep customization, integrations with industry tools."),
      p("HubSpot until you feel its limits. Salesforce when you need enterprise flexibility — but brace for ops cost.")),

    C("klaviyo-vs-mailchimp", "Klaviyo", "Mailchimp", "Email Marketing",
      "DTC-focused vs general-purpose email marketing.",
      "Klaviyo is built for e-commerce with deep Shopify integration and product-behavior-based segmentation. Mailchimp is general-purpose, cheaper at low volumes.",
      [("E-commerce integration", "Best in class", "Basic"),
       ("Segmentation", "Product/behavior deep", "Generic"),
       ("Price", "Higher at scale", "Cheaper at low volume"),
       ("Deliverability", "Strong", "Adequate")],
      p("E-commerce / DTC brand, want product-level triggers."),
      p("Small biz, non-ecommerce, simple newsletters."),
      p("Klaviyo for any serious DTC brand. Mailchimp for small non-ecommerce use.")),

    C("convertkit-vs-beehiiv", "ConvertKit", "Beehiiv", "Newsletters",
      "Two creator-focused newsletter platforms.",
      "ConvertKit (now Kit) is the incumbent for creators. Beehiiv is the newer challenger with strong free tier and growth features.",
      [("Free tier", "Up to 10K subs", "Up to 2.5K subs"),
       ("Pricing", "Starts $29/month", "Starts $39/month paid"),
       ("Ads / sponsorships", "Limited", "Native ad network"),
       ("Referral program", "Basic", "Built-in growth tools")],
      p("Established creator workflow, deeper automation."),
      p("New newsletter, want built-in sponsorships and referral mechanics."),
      p("Beehiiv for new newsletters. ConvertKit for creators already integrated with the ecosystem.")),

    # Ads platforms
    C("meta-vs-google-ads", "Meta Ads", "Google Ads", "Paid Ads",
      "Interrupt-based vs intent-based paid advertising.",
      "Meta is an interrupt channel (feed scrolling). Google Search is intent-based (user typing a query). Both matter; they reach different states.",
      [("Intent", "Low (interrupt)", "High (search)"),
       ("Creative", "Essential", "Less critical"),
       ("CPC range", "$0.50-5", "$1-50+"),
       ("Best for", "DTC consumer, visual", "Services, high-intent, B2B")],
      p("DTC, consumer products, visual demos, broad audience."),
      p("Services, high-intent B2B, capturing explicit demand."),
      p("Most businesses run both. Meta for demand creation, Google for demand capture.")),

    C("tiktok-vs-meta", "TikTok Ads", "Meta Ads", "Paid Ads",
      "The two big social ad platforms. Different creative rules, different audiences.",
      "TikTok is creative-first: native, UGC-style wins. Meta is more flexible but rewards produced creative less than it used to. TikTok skews younger; Meta skews older.",
      [("Audience", "Skews 18-34", "Broader demographics"),
       ("Creative", "Native UGC essential", "UGC or produced"),
       ("Targeting", "Algorithm-led (broad)", "Mix of broad + interest"),
       ("CPMs", "Competitive", "Higher for narrow targeting")],
      p("Younger audience, visual/entertainment product, creative-heavy team."),
      p("Broader demographics, DTC workhorse, more creative formats."),
      p("Most DTC brands run both. Meta is the anchor; TikTok is increasingly required for younger-skewing products.")),

    C("linkedin-vs-meta-b2b", "LinkedIn Ads", "Meta Ads", "Paid Ads",
      "B2B default vs broader consumer platform for B2B use cases.",
      "LinkedIn's targeting by role/company is unmatched for B2B. Meta can work for B2B via interest and behavioral targeting, usually cheaper, usually less precise.",
      [("B2B targeting", "Role, company, seniority", "Interest-based, looser"),
       ("CPC", "$5-30", "$0.50-5"),
       ("Audience intent", "Professional context", "Leisure context"),
       ("Lead quality", "Higher", "Variable")],
      p("B2B with clear role/seniority ICP, deal size >$10K ACV."),
      p("B2B with broader appeal, lower deal size, or when LinkedIn CPCs don't pay back."),
      p("LinkedIn for role-specific targeting. Meta for broader reach when the ICP is consumer-adjacent.")),

    C("google-search-vs-pmax", "Google Search", "Performance Max", "Paid Ads",
      "Manual keyword-based vs AI-driven automated Google campaigns.",
      "Search is high-intent, keyword-based, manual control. Pmax is AI-run across all Google inventory (Search, Shopping, Display, YouTube, Discover).",
      [("Control", "High (keywords, bids)", "Low (AI black box)"),
       ("Best for", "High-intent services", "E-commerce, mature advertisers"),
       ("Transparency", "Granular", "Limited reporting")],
      p("You want control, you're services/B2B, you have clear high-intent keywords."),
      p("E-commerce with feed, mature advertiser, want to let AI handle inventory distribution."),
      p("Services/B2B: Search. E-commerce: both, with Pmax doing Shopping + defaults and Search handling brand.")),

    C("meta-vs-youtube", "Meta Ads", "YouTube Ads", "Paid Ads",
      "Short-form interrupt feed vs longer-form video platform.",
      "Meta is fast-scroll, sound-off. YouTube is sound-on, longer watch times, more room for storytelling. Different creative, different conversion patterns.",
      [("Creative length", "6-30s typical", "15-90s typical"),
       ("Sound", "Off by default", "On by default"),
       ("Best for", "DTC, quick conversions", "Brand + longer consideration")],
      p("DTC, quick impulse purchases, iterative testing speed."),
      p("Longer consideration, video-first product demos, brand building."),
      p("Both together cover different audience moments. Budget typically 60% Meta, 20-30% YouTube for DTC.")),

    # Analytics
    C("ga4-vs-amplitude", "GA4", "Amplitude", "Analytics",
      "Free web analytics vs product analytics platform.",
      "GA4 is Google's free web analytics, succeeding Universal Analytics. Amplitude is a dedicated product analytics platform with deeper behavioral analysis.",
      [("Price", "Free tier", "Paid ($1000+/mo serious use)"),
       ("Focus", "Marketing + web", "Product behavior"),
       ("Event model", "Flexible but quirky", "Clean"),
       ("Funnels, cohorts", "Basic", "Strong")],
      p("Budget sensitive, marketing-focused, light product analytics."),
      p("Product-led SaaS, behavioral analysis, deep cohort work."),
      p("Most teams run both: GA4 for marketing attribution, Amplitude for product analytics.")),

    C("mixpanel-vs-amplitude", "Mixpanel", "Amplitude", "Analytics",
      "Two similar product analytics platforms.",
      "Both strong product analytics. Amplitude has better free tier; Mixpanel has simpler UX. Core features comparable.",
      [("Free tier", "Generous", "Generous"),
       ("UX", "Simpler", "More flexibility"),
       ("AI/ML", "Growing", "Strong")],
      p("Simpler UX, quick onboarding, faster to value."),
      p("More flexibility, stronger AI features."),
      p("Near-peers. Pick based on trial.")),

    C("triple-whale-vs-northbeam", "Triple Whale", "Northbeam", "Attribution",
      "DTC-focused attribution tools.",
      "Both serve e-commerce with multi-channel attribution. Triple Whale has broader product (dashboards, cohort, etc). Northbeam focuses on attribution precision.",
      [("Focus", "Full DTC dashboard", "Attribution + MMM"),
       ("Price", "From $129/mo", "From $850/mo (enterprise)"),
       ("MMM built-in", "No", "Yes")],
      p("DTC brands wanting an all-in-one analytics dashboard."),
      p("Brands focused on advanced attribution and MMM."),
      p("Triple Whale for growing DTC. Northbeam when attribution precision is a core concern.")),

    # Dev tools / Platforms
    C("vercel-vs-netlify", "Vercel", "Netlify", "Hosting",
      "Two leading frontend/JAMstack hosts.",
      "Vercel is tightly coupled to Next.js. Netlify is more framework-agnostic. Feature parity is mostly close.",
      [("Next.js", "First-class", "Good"),
       ("Build performance", "Very fast", "Very fast"),
       ("Edge functions", "Strong", "Strong"),
       ("Pricing", "From free, pay scale", "From free, pay scale")],
      p("Next.js-first, want the most seamless deployment."),
      p("Mixed frameworks, want platform-agnostic hosting."),
      p("Vercel for Next.js. Netlify for mixed stacks.")),

    C("supabase-vs-firebase", "Supabase", "Firebase", "BaaS",
      "Open-source Postgres-based BaaS vs Google's closed-source BaaS.",
      "Supabase is Postgres + auth + storage + functions, open-source. Firebase is NoSQL (Firestore), real-time, deeply integrated with Google services.",
      [("Database", "Postgres (SQL)", "Firestore (NoSQL)"),
       ("Real-time", "Good", "Best-in-class"),
       ("Self-hostable", "Yes", "No"),
       ("Ecosystem", "Growing", "Mature + Google integrations")],
      p("Want SQL/Postgres, want open-source, prefer not to lock into Google."),
      p("Want best real-time, Google ecosystem, don't need SQL."),
      p("Supabase for most new projects. Firebase for real-time-heavy apps or Google-native teams.")),

    C("postgres-vs-mongodb", "Postgres", "MongoDB", "Databases",
      "Relational workhorse vs document database.",
      "Postgres is the SQL standard with JSONB for flexibility. MongoDB is document-first, easier for schema-less data.",
      [("Model", "Relational + JSONB", "Document"),
       ("Query", "SQL", "Mongo query language"),
       ("Transactions", "Strong", "Good (multi-document)"),
       ("Ecosystem", "Vast", "Large")],
      p("Structured data, relations, SQL expertise, almost always the default."),
      p("Document-shaped data, schema-less workflows, rapid schema changes."),
      p("Postgres by default. MongoDB when document is a genuinely better fit (rare but real).")),

    C("redis-vs-memcached", "Redis", "Memcached", "Caching",
      "Full-featured vs minimal in-memory cache.",
      "Redis is a data structure server (strings, lists, sets, pub/sub). Memcached is a minimal key-value cache.",
      [("Data types", "Many", "Key-value only"),
       ("Persistence", "Optional", "None"),
       ("Pub/sub", "Yes", "No"),
       ("Use case", "Cache + more", "Pure cache")],
      p("More than just cache: pub/sub, queues, data structures."),
      p("Pure caching, max simplicity."),
      p("Redis for almost all new use cases. Memcached is legacy.")),

    # Frameworks
    C("langgraph-vs-crewai", "LangGraph", "CrewAI", "Agent Frameworks",
      "Graph-based vs role-based multi-agent frameworks.",
      "LangGraph uses explicit graph state machines. CrewAI uses role-based agent 'crews' with tasks. Different metaphors, different fits.",
      [("Metaphor", "State machine graph", "Role-based team"),
       ("Complexity", "More explicit control", "Simpler to start"),
       ("Production readiness", "Stronger", "Improving"),
       ("Multi-model", "Yes", "Yes")],
      p("Complex branching logic, production workflows, want explicit state."),
      p("Fast prototyping, role-based metaphor fits your problem."),
      p("LangGraph for production. CrewAI for prototype or when the role metaphor is genuinely your model.")),

    C("langchain-vs-llamaindex", "LangChain", "LlamaIndex", "LLM Frameworks",
      "General LLM orchestration vs data-focused framework.",
      "LangChain is a broad toolkit for LLM apps. LlamaIndex is specifically focused on connecting LLMs to data (RAG, knowledge bases, indexing).",
      [("Focus", "Broad LLM apps", "Data + RAG"),
       ("Abstractions", "Many, sometimes heavy", "Data-focused"),
       ("RAG features", "Good", "Best-in-class")],
      p("General agent apps, need broad LLM tooling."),
      p("RAG-heavy, complex data indexing, specialized retrieval strategies."),
      p("For RAG-focused apps, LlamaIndex has better primitives. For general agents, LangChain (or LangGraph).")),

    C("claude-code-vs-cursor", "Claude Code", "Cursor", "Coding Agents",
      "CLI-based vs IDE-integrated coding assistants.",
      "Claude Code is a CLI-based agent with file system and shell access. Cursor is an IDE (VS Code fork) with AI chat and edit features.",
      [("Form", "CLI", "IDE"),
       ("Autonomy", "High (multi-file, multi-step)", "Moderate (assisted edits)"),
       ("Setup", "Install + configure", "Download IDE"),
       ("Best for", "Autonomous tasks, SWE agent work", "Day-to-day coding assist")],
      p("Autonomous tasks, background engineering, multi-file refactors."),
      p("Everyday coding, inline completions, interactive editing."),
      p("Cursor for day-to-day dev. Claude Code for autonomous agent work.")),

    C("aider-vs-cursor", "Aider", "Cursor", "Coding Agents",
      "Open-source CLI coding assistant vs AI-powered IDE.",
      "Aider is a CLI-based git-aware coding assistant. Cursor is an IDE with native AI.",
      [("Form", "CLI", "IDE"),
       ("Price", "Free + API costs", "$20/month"),
       ("Model flexibility", "Bring your own", "Built-in options")],
      p("Terminal-first workflow, model flexibility, open-source preference."),
      p("VS Code workflow, integrated experience, managed billing."),
      p("Cursor for smoothness, Aider for flexibility and savings on API costs.")),

    # Sales / CRM
    C("pipedrive-vs-hubspot", "Pipedrive", "HubSpot", "CRM",
      "Sales-focused lean CRM vs full-stack marketing+sales+service.",
      "Pipedrive is simple, sales-first. HubSpot is broader with marketing and service modules.",
      [("Sales features", "Strong", "Strong"),
       ("Marketing tools", "Limited", "Full marketing hub"),
       ("Price", "From $15/user", "From $0, scales up"),
       ("Ease of use", "Very simple", "More features to navigate")],
      p("Pure sales team, want minimal CRM without marketing tools."),
      p("Want marketing + sales + service in one platform."),
      p("Pipedrive for lean sales teams. HubSpot for broader go-to-market alignment.")),

    C("close-vs-hubspot", "Close", "HubSpot", "CRM",
      "Inside-sales-focused vs full-stack CRM.",
      "Close is built for calling/SDR-heavy teams with powerful call and email features. HubSpot is broader.",
      [("Calling", "Native + strong", "Add-on"),
       ("Cold email", "Built-in", "Add-on"),
       ("Marketing hub", "None", "Full"),
       ("Price", "From $49/user", "From $0, scales")],
      p("Inside sales team, heavy calling + cold email, want one tool."),
      p("Marketing + sales integration, service functions."),
      p("Close if your team lives on phones and cold email. HubSpot if marketing alignment matters.")),

    # SEO tools
    C("ahrefs-vs-semrush", "Ahrefs", "Semrush", "SEO Tools",
      "The two flagship SEO toolkits.",
      "Both cover keyword research, backlink analysis, rank tracking, site audits. Ahrefs has historically better backlink data; Semrush has stronger PPC features.",
      [("Backlinks", "Best in class", "Solid"),
       ("Keywords", "Strong", "Strong"),
       ("PPC tools", "Basic", "Stronger"),
       ("Price", "From $129/mo", "From $139/mo"),
       ("Content tools", "Solid", "Slightly richer")],
      p("Backlink analysis, cleaner UI, speed."),
      p("Combined SEO + PPC, content marketing tools."),
      p("Both work. Ahrefs for SEO purists, Semrush for marketing generalists.")),

    C("ahrefs-vs-moz", "Ahrefs", "Moz", "SEO Tools",
      "Modern SEO toolkit vs long-standing alternative.",
      "Ahrefs has better backlink and keyword data today. Moz pioneered SEO metrics (Domain Authority) but has lost ground.",
      [("Data freshness", "Excellent", "Good"),
       ("Backlinks", "Best", "Solid"),
       ("Price", "From $129/mo", "From $99/mo")],
      p("Serious SEO work, accurate data matters."),
      p("Budget-conscious, light SEO needs."),
      p("Ahrefs for most serious SEO teams. Moz has fallen behind on core metrics.")),

    C("screaming-frog-vs-sitebulb", "Screaming Frog", "Sitebulb", "SEO Tools",
      "Two technical SEO crawlers.",
      "Screaming Frog is the industry standard for SEO crawling. Sitebulb offers more opinionated reports and visualizations.",
      [("Crawl power", "Extensive", "Strong"),
       ("Reporting", "Raw data-focused", "Analysis + visuals"),
       ("Price", "£169/yr", "$14-52/mo")],
      p("Raw crawl control, bulk data analysis."),
      p("Guided audit reports, nicer UX."),
      p("Screaming Frog for technical SEO pros. Sitebulb for teams wanting cleaner reports.")),

    # Productivity
    C("notion-vs-linear", "Notion", "Linear", "Productivity",
      "Docs + databases vs issue tracker.",
      "Notion is flexible docs/databases/project mgmt. Linear is opinionated, fast issue tracking for software teams.",
      [("Primary", "Knowledge base + DB", "Issue tracking"),
       ("Performance", "Can get slow", "Very fast"),
       ("Best for", "Wikis, mixed use cases", "Engineering teams")],
      p("Wiki, mixed-use, cross-team docs."),
      p("Engineering issue tracking."),
      p("Use both: Linear for engineering work, Notion for docs.")),

    C("slack-vs-teams", "Slack", "Microsoft Teams", "Communication",
      "Developer-friendly vs enterprise-integrated chat.",
      "Slack has better UX and third-party integrations. Teams is bundled with Microsoft 365 and has deeper Office integration.",
      [("UX", "Polished", "Improving"),
       ("Integrations", "Vast", "Microsoft-deep"),
       ("Price", "$$", "Included in M365")],
      p("Tech-forward teams, startups, deep third-party integrations."),
      p("Microsoft 365 orgs, included cost."),
      p("Slack if you can choose. Teams when bundled/free via M365.")),

    C("zoom-vs-google-meet", "Zoom", "Google Meet", "Video Conferencing",
      "Dedicated video conferencing vs Google Workspace bundle.",
      "Zoom is feature-rich and the default in many industries. Google Meet is included with Workspace and improving fast.",
      [("Features", "Most features", "Solid features"),
       ("Price", "$$", "Included in Workspace"),
       ("Ecosystem", "Third-party integrations", "Google suite")],
      p("Advanced features (webinars, breakout rooms), clients expect Zoom links."),
      p("Google Workspace team, simpler needs."),
      p("Zoom for breadth. Meet for simplicity + bundled cost.")),

    # Design tools
    C("figma-vs-sketch", "Figma", "Sketch", "Design Tools",
      "Cloud-native vs Mac-only design tool.",
      "Figma has largely won this war with real-time collaboration and browser access. Sketch is mac-only, feature-rich, but lost ground.",
      [("Platform", "All platforms", "Mac only"),
       ("Collaboration", "Real-time, best in class", "Needs plugins"),
       ("Pricing", "Free tier + paid", "$$")],
      p("Teams, cross-platform, real-time collab."),
      p("Mac-only team, established Sketch workflows."),
      p("Figma for nearly all new projects.")),

    C("figma-vs-canva", "Figma", "Canva", "Design Tools",
      "Professional design tool vs accessible design for non-designers.",
      "Figma is for designers. Canva is for non-designers who need to make decent-looking marketing content.",
      [("Audience", "Designers, teams", "Marketers, non-designers"),
       ("Output quality ceiling", "High", "Moderate"),
       ("Learning curve", "Moderate", "Easy"),
       ("Templates", "Limited", "Tons")],
      p("Professional design work, detailed UI mockups, components."),
      p("Marketing visuals, social posts, presentations by non-designers."),
      p("Figma for product/UI work. Canva for marketing collateral.")),

    # Automation
    C("zapier-vs-make", "Zapier", "Make", "Automation",
      "Two leading automation platforms.",
      "Zapier has the most integrations and simpler UX. Make (formerly Integromat) is more powerful and cheaper at scale but has a steeper learning curve.",
      [("Integrations", "7000+", "1500+"),
       ("Ease of use", "Easier", "More powerful"),
       ("Price at scale", "Expensive", "Cheaper"),
       ("Complex logic", "Limited", "Strong")],
      p("Simple linear automations, many integrations."),
      p("Complex workflows with branching, iteration, transformation."),
      p("Zapier for beginners. Make for serious automation builders.")),

    C("make-vs-n8n", "Make", "n8n", "Automation",
      "Closed-source hosted vs open-source self-hostable automation.",
      "Make is a hosted product. n8n is open-source, self-hostable, similar capability.",
      [("Hosting", "Managed", "Self-host or cloud"),
       ("Price", "Usage-based", "Free (self-host) or paid"),
       ("Data privacy", "SaaS", "Self-hostable for full control")],
      p("No-ops preference."),
      p("Self-hosting, data privacy, full control."),
      p("n8n for technical teams with self-host capacity. Make for faster time-to-value.")),

    # Project mgmt
    C("asana-vs-monday", "Asana", "Monday", "Project Management",
      "Two popular PM tools.",
      "Both cover tasks, boards, timelines. Asana is stronger on task-level detail; Monday has a broader, spreadsheet-like flexibility.",
      [("Views", "Task-focused", "Spreadsheet-style flexibility"),
       ("Learning curve", "Moderate", "Moderate"),
       ("Price", "$$", "$$")],
      p("Teams organized around tasks + projects, clean workflows."),
      p("Teams wanting flexible, customizable board structures."),
      p("Both work. Preference is often team culture.")),

    C("asana-vs-clickup", "Asana", "ClickUp", "Project Management",
      "Focused PM tool vs everything-platform.",
      "Asana is focused on project management. ClickUp tries to be PM + docs + chat + goals. More features; sometimes more complexity.",
      [("Scope", "PM only", "PM + docs + chat + goals"),
       ("Feature depth", "High in PM", "Broad across many"),
       ("Learning curve", "Moderate", "Steep")],
      p("Want focused PM, clean UX."),
      p("Want one tool to replace many; willing to invest in setup."),
      p("Asana for focused teams. ClickUp for teams consolidating multiple tools.")),

    # Writing
    C("grammarly-vs-hemingway", "Grammarly", "Hemingway", "Writing Tools",
      "Grammar checker vs readability editor.",
      "Grammarly catches errors, suggests improvements, works everywhere. Hemingway focuses on making prose bolder and clearer.",
      [("Focus", "Grammar + style", "Readability + clarity"),
       ("Integration", "Everywhere", "Standalone app"),
       ("Price", "Free tier + premium", "Free + $20 desktop app")],
      p("Daily writing, catching errors everywhere."),
      p("Polishing already-drafted prose for impact."),
      p("Both. Grammarly for everyday. Hemingway as a final editing pass.")),

    C("notion-vs-obsidian", "Notion", "Obsidian", "Notes",
      "Cloud-first notes/database vs local-first linked notes.",
      "Notion is cloud-collaborative with databases. Obsidian is local-first, markdown, with strong linking for personal knowledge management.",
      [("Storage", "Cloud", "Local (syncable)"),
       ("Collaboration", "Strong", "Limited"),
       ("Flexibility", "Databases + pages", "Markdown + plugins")],
      p("Team collaboration, databases, structured docs."),
      p("Personal knowledge management, local ownership of data."),
      p("Notion for team. Obsidian for personal deep thinking.")),

    # Ecommerce
    C("shopify-vs-woocommerce", "Shopify", "WooCommerce", "Ecommerce Platforms",
      "Hosted SaaS vs WordPress plugin.",
      "Shopify is hosted, opinionated, fast to start. WooCommerce requires WordPress knowledge, more customizable, cheaper at scale.",
      [("Hosting", "Managed SaaS", "Self-hosted WordPress"),
       ("Customization", "Themes + apps", "Unlimited (WP ecosystem)"),
       ("Monthly cost", "$29-399", "Hosting only (~$20-500)"),
       ("Learning curve", "Low", "Moderate (WP required)")],
      p("Speed to launch, no-ops preference, design-forward."),
      p("Full control, WordPress already in stack, cost sensitivity."),
      p("Shopify for most new DTC. WooCommerce for WP-native teams.")),

    # Scheduling
    C("calendly-vs-savvycal", "Calendly", "SavvyCal", "Scheduling",
      "Market leader vs design-forward challenger.",
      "Calendly is the default. SavvyCal has better UX around overlays and team availability.",
      [("Market share", "Dominant", "Growing"),
       ("UX", "Functional", "Polished"),
       ("Availability overlap", "Basic", "Excellent"),
       ("Price", "Free + paid", "$$")],
      p("Familiarity, integrations, biggest ecosystem."),
      p("Better UX, overlay tools for group scheduling."),
      p("Either works. SavvyCal if you value UX polish.")),

    # Cold email / outreach extras
    C("apollo-vs-instantly", "Apollo", "Instantly", "Outreach",
      "All-in-one data + outreach vs dedicated cold email tool.",
      "Apollo bundles database + basic sequencing. Instantly is a pure cold email platform with deeper deliverability focus.",
      [("Primary function", "Database + outreach", "Cold email specialist"),
       ("Deliverability focus", "Good", "Best in class for cold"),
       ("Data built-in", "Yes", "No (bring your own)"),
       ("Multi-inbox", "Limited", "Unlimited plans")],
      p("Want data + outreach in one tool, simplicity."),
      p("Serious cold email volume, need top deliverability, already have data."),
      p("Apollo to start. Instantly when you're scaling cold email operations.")),

    # RAG vs fine-tuning
    C("rag-vs-finetuning", "RAG", "Fine-tuning", "AI Techniques",
      "Retrieval-augmented generation vs fine-tuning an LLM.",
      "RAG gives models access to new facts. Fine-tuning changes model behavior/style/format. They solve different problems.",
      [("Changes", "What facts the model can access", "How the model behaves"),
       ("Cost", "Low (infrastructure)", "High (training)"),
       ("Update frequency", "Anytime (reindex)", "Rare (retrain)"),
       ("Use case", "Facts, docs, grounding", "Style, format, specialized tasks")],
      p("You need the model to answer from specific (changing) facts."),
      p("You need stable output format/style the model can't get via prompting."),
      p("Start with RAG. Fine-tune only when RAG isn't enough and the behavior you need is stable.")),

    C("rag-vs-long-context", "RAG", "Long-context window", "AI Techniques",
      "Fetch-relevant-context vs stuff-everything-in-context.",
      "RAG retrieves a small relevant subset. Long context (1M tokens) can fit entire documents. Different tradeoffs on cost, latency, and quality.",
      [("Cost per query", "Low", "High (full context billed)"),
       ("Latency", "Lower", "Higher"),
       ("Quality", "Depends on retrieval", "Can degrade mid-context"),
       ("Freshness", "Easy to refresh", "Same")],
      p("Large corpora, recurring queries, cost sensitivity."),
      p("One-off analysis of a single long document."),
      p("For production systems, RAG. Long-context is for specific use cases, not a general replacement.")),

    # Agents
    C("agent-vs-workflow", "Agent", "Workflow", "AI Patterns",
      "Autonomous reasoning loops vs deterministic step-by-step pipelines.",
      "An agent reasons about what to do next. A workflow has hardcoded steps. Different reliability, cost, and appropriate use cases.",
      [("Steps", "Dynamic (agent decides)", "Fixed (predefined)"),
       ("Reliability", "Variable", "Predictable"),
       ("Cost", "Higher (multiple LLM calls)", "Lower"),
       ("Debug", "Harder", "Easier")],
      p("Task with dynamic branching, exploration needed."),
      p("Known sequence of steps, reliability matters."),
      p("Most production 'agents' should actually be workflows. Use agents only when the branching is genuinely dynamic.")),

    # Content platforms
    C("substack-vs-beehiiv", "Substack", "Beehiiv", "Newsletters",
      "Paid newsletters focus vs creator growth focus.",
      "Substack pioneered paid newsletters with a built-in audience. Beehiiv leans into growth tools (referrals, ads, cross-promotion).",
      [("Paid subs", "Core feature", "Supported"),
       ("Growth tools", "Limited", "Strong"),
       ("Discovery", "Substack network", "SEO + referral tools"),
       ("Revenue share", "10%", "None on paid plans")],
      p("Paid subscriptions, Substack's built-in discovery."),
      p("Growth tools, sponsorship revenue, SEO focus."),
      p("Substack for paid newsletters in established niches. Beehiiv for newer newsletters focused on scale.")),

    C("medium-vs-substack", "Medium", "Substack", "Publishing",
      "Platform with algorithm vs owned-audience newsletter.",
      "Medium offers algorithmic distribution but you don't own the audience. Substack is newsletter-first — your audience is yours via email.",
      [("Audience ownership", "Limited (Medium's readers)", "You own the list"),
       ("Distribution", "Algorithmic boost possible", "Email + Substack network"),
       ("Monetization", "Partner Program", "Direct subscriptions")],
      p("Already-established writer, want algorithmic reach, hate managing lists."),
      p("Want to own your audience, build direct relationship, long-term moat."),
      p("Substack for career writers building audiences. Medium for hobby writers who want occasional reach.")),

    # Sales tools extras
    C("gong-vs-chorus", "Gong", "Chorus", "Sales Intelligence",
      "Two leading sales conversation intelligence platforms.",
      "Both record and analyze sales calls. Gong has larger market share and more AI features. Chorus (now part of ZoomInfo) has deep ZoomInfo integration.",
      [("AI coaching", "Strong", "Solid"),
       ("Integration", "Broad", "Deep ZoomInfo"),
       ("Price", "Enterprise", "Enterprise")],
      p("Standalone sales org, best-in-class AI."),
      p("Already in ZoomInfo ecosystem, tight integration."),
      p("Gong for most enterprise sales teams. Chorus for ZoomInfo-centric orgs.")),

    # Hosting
    C("aws-vs-gcp", "AWS", "GCP", "Cloud",
      "Market leader vs Google's cloud offering.",
      "AWS has the broadest product catalog and ecosystem. GCP is often better for data/AI workloads.",
      [("Breadth", "Largest catalog", "Strong catalog"),
       ("AI/ML tools", "Good", "Excellent (Vertex, TPUs)"),
       ("Pricing", "Complex", "Often simpler, often cheaper")],
      p("Breadth of services, largest community, default choice."),
      p("AI/ML-heavy workloads, simpler pricing, Google ecosystem."),
      p("AWS for most. GCP for AI-centric teams or if you prefer Google's tooling.")),

    C("aws-vs-azure", "AWS", "Azure", "Cloud",
      "Leader vs enterprise-focused competitor.",
      "AWS has broader tooling. Azure wins enterprise deals via Microsoft ecosystem (AD, Office, Windows Server).",
      [("Services", "Broadest", "Comprehensive"),
       ("Enterprise integration", "Strong", "Best for MS shops"),
       ("Developer preference", "Strong", "Growing")],
      p("Pure tech, startups, broadest services."),
      p("Microsoft-stack enterprises, AD integration."),
      p("AWS for most. Azure for Microsoft-native orgs.")),

    # Monitoring
    C("datadog-vs-new-relic", "Datadog", "New Relic", "Monitoring",
      "Two observability platforms.",
      "Both cover APM, logs, infrastructure. Datadog has broader product; New Relic has pricing that's often easier at scale.",
      [("Breadth", "Very wide", "Strong"),
       ("Pricing", "Complex, can be expensive", "Usage-based, predictable"),
       ("UX", "Polished", "Functional")],
      p("Many monitoring needs in one platform."),
      p("Predictable pricing, APM focus."),
      p("Datadog for breadth. New Relic for APM-centric workloads.")),

    # Email / deliverability
    C("sendgrid-vs-postmark", "SendGrid", "Postmark", "Transactional Email",
      "Volume-focused vs deliverability-focused.",
      "SendGrid handles very high volumes. Postmark has a reputation for stronger transactional deliverability.",
      [("Deliverability", "Good", "Best in class"),
       ("Pricing", "Cheaper at volume", "Premium"),
       ("Marketing features", "Some", "None (pure transactional)")],
      p("High-volume, cost-sensitive, mixed use."),
      p("Transactional only, deliverability is the priority."),
      p("Postmark for pure transactional. SendGrid for volume + marketing mix.")),

    # UI component libs
    C("tailwind-vs-bootstrap", "Tailwind CSS", "Bootstrap", "CSS Frameworks",
      "Utility-first vs component-first CSS.",
      "Tailwind provides low-level utility classes. Bootstrap provides prebuilt components.",
      [("Approach", "Utility-first", "Component-first"),
       ("Customization", "Extreme", "Via overrides"),
       ("Learning curve", "Steeper upfront", "Faster to start")],
      p("Want custom designs, modern DX, don't want to override components."),
      p("Want out-of-the-box components, fast prototyping."),
      p("Tailwind for new projects where design matters. Bootstrap for admin panels and internal tools.")),

    # Ecommerce
    C("stripe-vs-paypal", "Stripe", "PayPal", "Payments",
      "Developer-first vs consumer-first payment processor.",
      "Stripe is built for developers with rich APIs. PayPal is familiar to consumers and often preferred for trust.",
      [("Developer API", "Best in class", "Solid"),
       ("Consumer trust", "Strong", "Very strong"),
       ("Fees", "2.9% + $0.30", "Similar")],
      p("Building custom checkout, developer-first, subscription business."),
      p("Consumer trust matters, marketplace where buyers prefer PayPal."),
      p("Stripe for most SaaS/modern DTC. Offer PayPal as a secondary option if your audience expects it.")),

    # AI/Tools
    C("notion-ai-vs-chatgpt", "Notion AI", "ChatGPT", "AI Writing",
      "In-app AI in Notion vs standalone AI chat.",
      "Notion AI is convenient for people working in Notion. ChatGPT is a more powerful general-purpose AI.",
      [("Integration", "Notion-only", "Everywhere (app + API)"),
       ("Power", "Good", "More capable model access"),
       ("Price", "$10/user Notion addon", "$20/mo")],
      p("You live in Notion, want inline AI."),
      p("General-purpose use, maximum capability, multiple contexts."),
      p("ChatGPT for general. Notion AI as a convenience layer if you're already there.")),

    # Comms
    C("telegram-vs-whatsapp", "Telegram", "WhatsApp", "Messaging",
      "Power-user messenger vs dominant global messenger.",
      "Telegram has stronger creator/community features. WhatsApp has the largest user base and business API.",
      [("Channels + groups", "Strong", "Decent"),
       ("Business API", "Growing", "Mature (WhatsApp Business)"),
       ("Encryption default", "No (opt in)", "Yes (E2E default)")],
      p("Broadcast channels, large communities, creator tools."),
      p("Reach widest audience, business messaging at scale."),
      p("WhatsApp for business messaging. Telegram for community + broadcast.")),

    # Analytics extras
    C("posthog-vs-amplitude", "PostHog", "Amplitude", "Product Analytics",
      "Open-source product analytics vs managed leader.",
      "PostHog is open-source, self-hostable, includes analytics + feature flags + session replay. Amplitude is a managed specialist.",
      [("Hosting", "Self or cloud", "Cloud only"),
       ("Scope", "Analytics + flags + replay", "Analytics-focused"),
       ("Price", "Usage-based", "Usage-based")],
      p("Want all-in-one (analytics + flags + replay), cost-conscious, self-host option."),
      p("Analytics depth and UX, comfortable paying for specialization."),
      p("PostHog for startups and teams consolidating. Amplitude for analytics-focused mature teams.")),

    # Testing
    C("cypress-vs-playwright", "Cypress", "Playwright", "E2E Testing",
      "Two leading end-to-end testing frameworks.",
      "Cypress has been the incumbent with great DX. Playwright (from Microsoft) is newer, faster, cross-browser, cross-language.",
      [("Browsers", "Chrome-family + Firefox", "All browsers + mobile"),
       ("Language", "JavaScript", "JS, Python, C#, Java"),
       ("Speed", "Good", "Faster"),
       ("Parallel testing", "Paid", "Free")],
      p("JavaScript-only team, established Cypress workflows."),
      p("Cross-browser testing, cross-language teams, performance matters."),
      p("Playwright for new projects. Cypress when existing Cypress suite works.")),

    # Model training
    C("pytorch-vs-tensorflow", "PyTorch", "TensorFlow", "ML Frameworks",
      "Research-friendly vs production-hardened ML frameworks.",
      "PyTorch dominates research and modern LLM work. TensorFlow has better production deployment tooling historically.",
      [("Research share", "Dominant", "Declining"),
       ("Production tools", "Improving", "Mature (TF Serving, TFX)"),
       ("Ecosystem in 2026", "AI-native", "Production-focused")],
      p("Modern ML/AI work, LLMs, research, close to latest papers."),
      p("Legacy production ML, TF-integrated stack."),
      p("PyTorch for nearly all new work. TF for legacy maintenance.")),

    # Data warehouses
    C("snowflake-vs-bigquery", "Snowflake", "BigQuery", "Data Warehouses",
      "Multi-cloud vs Google's native warehouse.",
      "Snowflake is cloud-agnostic and handles complex workloads. BigQuery is Google-native and simpler.",
      [("Cloud", "AWS/GCP/Azure", "GCP only"),
       ("Pricing", "Compute-separated", "Usage-based, simpler"),
       ("Feature depth", "Rich", "Solid")],
      p("Multi-cloud, complex workloads, cost optimization."),
      p("Google-native, simpler setup, analytics-first."),
      p("Snowflake for multi-cloud + sophistication. BigQuery for Google-shop simplicity.")),

    # Attribution
    C("triple-whale-vs-rockerbox", "Triple Whale", "Rockerbox", "Attribution",
      "DTC-focused vs enterprise-focused attribution.",
      "Triple Whale is great for growing DTC. Rockerbox handles larger, more complex multi-channel scenarios.",
      [("Scale", "DTC startups to mid-market", "Mid-market to enterprise"),
       ("MMM", "Light", "Strong"),
       ("Pricing", "$129+/mo", "Higher")],
      p("Growing DTC, dashboard focus, simpler attribution."),
      p("Mid/large brand with complex multi-channel needs."),
      p("Triple Whale for smaller DTC. Rockerbox when attribution precision at scale matters.")),

    # Cold email deliverability
    C("warmy-vs-mailwarm", "Warmy", "Mailwarm", "Email Warming",
      "Two dedicated inbox warming services.",
      "Both warm sender reputation. Warmy has AI-powered engagement patterns and better analytics. Mailwarm has a large network.",
      [("Network size", "Large", "Large"),
       ("Analytics", "Detailed", "Standard"),
       ("Price", "$49-229/mo", "$69-199/mo")],
      p("Analytics-driven warming, AI engagement patterns."),
      p("Established service, larger network."),
      p("Both work. Most serious users just use the built-in warming in Instantly/Smartlead.")),

    C("cold-email-tool-vs-builtin-warming", "Dedicated warming", "Built-in warming", "Deliverability",
      "Standalone warming services vs warming bundled with your cold email tool.",
      "Standalone tools (Warmy, Mailwarm, Mailreach) are dedicated. Instantly/Smartlead/Lemlist include warming. Same outcome mostly.",
      [("Cost", "Extra subscription", "Included"),
       ("Quality", "Sometimes better", "Good enough for most"),
       ("Setup complexity", "Extra account", "One tool")],
      p("Extreme deliverability sensitivity, want dedicated tool."),
      p("Cost-sensitive, bundled convenience."),
      p("Built-in warming in modern cold email tools is good enough for almost everyone.")),
]


if __name__ == "__main__":
    build_comparisons(COMPARISONS)
    print(f"Built {len(COMPARISONS)} + 1 index = {len(COMPARISONS) + 1} pages")
