#!/usr/bin/env python3
"""100 glossary terms across AI, Marketing, SEO, Sales, Ops."""
from _build_glossary import build_glossary


def T(slug, term, topic, definition, detail="", related=None):
    return {'slug': slug, 'term': term, 'topic': topic, 'definition': definition,
            'detail': f'<p class="gloss-detail">{detail}</p>' if detail else '',
            'related': related or []}


TERMS = [
    # AI (25)
    T("llm", "LLM", "AI",
      "Large Language Model. A neural network trained on massive text data that predicts the next token in a sequence, producing coherent language output.",
      "Examples: Claude, GPT-4, Gemini. Modern LLMs have tens to hundreds of billions of parameters. Foundation of most modern AI applications.",
      ["transformer", "token", "context-window", "foundation-model"]),
    T("agent", "AI Agent", "AI",
      "An LLM in a loop with tools. The LLM reasons, picks actions, executes via tools, observes results, and continues until a goal is reached.",
      "Distinct from a single LLM call. Agents can browse, call APIs, write files, coordinate sub-tasks.",
      ["llm", "tool-use", "react"]),
    T("react", "ReAct", "AI",
      "Reasoning + Acting. The canonical agent pattern: think, act (call tool), observe result, repeat.",
      "Introduced in 2022, still the foundation for most production agents.",
      ["agent", "tool-use"]),
    T("rag", "RAG", "AI",
      "Retrieval-Augmented Generation. Fetch relevant context from a knowledge base, paste into the LLM prompt, generate an answer grounded in that context.",
      "The dominant pattern for giving LLMs access to private or up-to-date information without fine-tuning.",
      ["vector-database", "embedding", "llm"]),
    T("embedding", "Embedding", "AI",
      "A vector representation of text where semantically similar text produces similar vectors.",
      "Embeddings power semantic search. Models like text-embedding-3 from OpenAI produce these.",
      ["vector-database", "rag", "semantic-search"]),
    T("vector-database", "Vector Database", "AI",
      "A database optimized to store and query high-dimensional vectors by similarity, not by exact match.",
      "Examples: Pinecone, Weaviate, Qdrant, pgvector. Essential infrastructure for RAG.",
      ["embedding", "rag", "semantic-search"]),
    T("semantic-search", "Semantic Search", "AI",
      "Search based on meaning rather than exact keywords. Uses embeddings to match intent.",
      "",
      ["embedding", "vector-database", "bm25"]),
    T("bm25", "BM25", "AI",
      "Classical keyword-based information retrieval algorithm. Scores documents by term frequency and document rarity.",
      "Still essential alongside semantic search. Hybrid retrieval (BM25 + dense) outperforms either alone.",
      ["semantic-search", "rag"]),
    T("prompt-engineering", "Prompt Engineering", "AI",
      "The craft of designing LLM prompts to reliably produce desired outputs.",
      "Includes system prompts, examples, formatting, constraints, and chain-of-thought structuring.",
      ["llm", "system-prompt", "few-shot"]),
    T("system-prompt", "System Prompt", "AI",
      "The instructions given to an LLM defining its role, behavior, and constraints. Appears before user messages.",
      "Sets the agent's persona, rules, tools available, output format.",
      ["prompt-engineering", "llm"]),
    T("few-shot", "Few-Shot Prompting", "AI",
      "Giving the LLM 2-10 examples of desired input-output pairs before the actual task.",
      "Reliable technique for getting structured outputs or specific styles without fine-tuning.",
      ["prompt-engineering", "zero-shot"]),
    T("zero-shot", "Zero-Shot", "AI",
      "Asking an LLM to do a task with no examples, relying entirely on task description.",
      "Modern large models handle many tasks zero-shot. Few-shot still helps for unusual outputs.",
      ["few-shot", "prompt-engineering"]),
    T("tool-use", "Tool Use", "AI",
      "An LLM's ability to request function/API calls and incorporate results into its reasoning.",
      "Also called function calling. Foundation of agentic behavior.",
      ["agent", "react", "function-calling"]),
    T("function-calling", "Function Calling", "AI",
      "The API pattern where LLMs emit structured requests to call developer-defined functions.",
      "OpenAI, Claude, and Gemini all support native function calling.",
      ["tool-use", "agent"]),
    T("fine-tuning", "Fine-Tuning", "AI",
      "Training an existing model on additional data to adapt it to a specific task or style.",
      "Different from prompting or RAG. Changes the model's weights. Expensive; used when prompting can't achieve needed behavior.",
      ["llm", "training"]),
    T("token", "Token", "AI",
      "Unit of text processed by LLMs. Roughly 3-4 characters or 0.75 words in English.",
      "Pricing and context limits are measured in tokens.",
      ["context-window", "llm"]),
    T("context-window", "Context Window", "AI",
      "Maximum number of tokens an LLM can process in a single request (input + output combined).",
      "Ranges from 4K (old models) to 1M+ (Gemini Pro, Claude Sonnet). Longer windows = more context but slower and more expensive.",
      ["token", "llm"]),
    T("hallucination", "Hallucination", "AI",
      "An LLM producing false information that sounds plausible. The model invents facts.",
      "Mitigated by RAG (ground in real context), better prompts, and verification systems.",
      ["rag", "grounding", "llm"]),
    T("grounding", "Grounding", "AI",
      "Ensuring LLM responses are anchored in specific factual context rather than the model's internal beliefs.",
      "RAG is a grounding technique. Citations are a grounding signal.",
      ["rag", "hallucination"]),
    T("chunking", "Chunking", "AI",
      "Splitting documents into smaller pieces for retrieval. Affects RAG quality significantly.",
      "Strategies: fixed-size, semantic, recursive, structure-aware. Covered in the RAG section.",
      ["rag", "embedding"]),
    T("reranking", "Reranking", "AI",
      "A second-stage model that reorders retrieved documents by relevance. Typically uses a cross-encoder.",
      "Adds 10-30% improvement over initial retrieval alone. Standard in production RAG.",
      ["rag", "retrieval"]),
    T("mcp", "MCP", "AI",
      "Model Context Protocol. Anthropic's open protocol for LLMs to connect to external tools and data sources.",
      "Think of it as a standard plug for AI tools. Growing ecosystem of MCP servers.",
      ["tool-use", "agent"]),
    T("transformer", "Transformer", "AI",
      "The neural network architecture underlying modern LLMs. Uses self-attention to process sequences.",
      "Introduced in 2017 'Attention Is All You Need' paper. Foundation of GPT, Claude, Gemini, all major LLMs.",
      ["llm", "attention"]),
    T("attention", "Attention Mechanism", "AI",
      "The mechanism by which transformers weight the importance of different parts of input when producing output.",
      "Self-attention lets the model relate every token to every other token.",
      ["transformer", "llm"]),
    T("foundation-model", "Foundation Model", "AI",
      "A large pre-trained model that can be adapted to many tasks via prompting or fine-tuning.",
      "GPT-4, Claude, Gemini are foundation models. Distinct from narrow task-specific models.",
      ["llm", "fine-tuning"]),

    # MARKETING (25)
    T("cac", "CAC", "Marketing",
      "Customer Acquisition Cost. Total spend to acquire one customer. Includes ads, salaries, tools, commissions.",
      "Compare to LTV to judge unit economics. Blended CAC is usually truer than channel-specific.",
      ["ltv", "ltv-cac-ratio", "payback-period"]),
    T("ltv", "LTV", "Marketing",
      "Lifetime Value. Total gross profit a customer generates over their relationship with you.",
      "Use gross profit, not revenue. Use observed LTV, not projected, until you have 18+ months of data.",
      ["cac", "ltv-cac-ratio"]),
    T("ltv-cac-ratio", "LTV:CAC", "Marketing",
      "Ratio of Lifetime Value to Customer Acquisition Cost. Below 3:1 is fragile, 5:1+ is healthy.",
      "The single most important unit economic for paid advertising businesses.",
      ["ltv", "cac", "payback-period"]),
    T("payback-period", "Payback Period", "Marketing",
      "How long it takes to recover CAC in gross profit from a customer.",
      "Under 12 months is healthy. Over 24 creates cash-flow pressure.",
      ["cac", "ltv"]),
    T("cpm", "CPM", "Marketing",
      "Cost Per Mille. What you pay per 1,000 ad impressions.",
      "Varies dramatically by platform and audience: $1-5 (Display) to $150+ (LinkedIn executives).",
      ["cpc", "cpa"]),
    T("cpc", "CPC", "Marketing",
      "Cost Per Click. Average cost for each click on your ad.",
      "Derived from CPM and CTR. Typical ranges: $0.50-5 (Meta), $5-30 (LinkedIn), $1-50+ (Google keywords).",
      ["cpm", "ctr", "cpa"]),
    T("ctr", "CTR", "Marketing",
      "Click-Through Rate. Percentage of impressions that resulted in a click.",
      "Signal of creative quality and audience match. 1-3% is average on paid social.",
      ["cpc", "cpm"]),
    T("cpa", "CPA", "Marketing",
      "Cost Per Acquisition. Cost for one conversion event (lead, sale, signup).",
      "Sometimes used interchangeably with CAC, but CAC typically includes more overhead.",
      ["cac", "cpc"]),
    T("roas", "ROAS", "Marketing",
      "Return On Ad Spend. Revenue divided by ad spend, expressed as a multiple.",
      "Target varies by margin: 2-3x for high-margin, 5-10x for low-margin.",
      ["mer", "cac"]),
    T("mer", "MER", "Marketing",
      "Media Efficiency Ratio. Total revenue divided by total ad spend. Blended across all channels.",
      "The truth metric when attribution is noisy. Can't be faked by platform double-counting.",
      ["roas", "attribution"]),
    T("attribution", "Attribution", "Marketing",
      "Determining which marketing touchpoints get credit for a conversion.",
      "Post iOS 14 and cookie deprecation, attribution is noisier. Most advertisers use a mix of platform attribution + MER + incrementality tests.",
      ["mer", "incrementality", "mmm"]),
    T("incrementality", "Incrementality Testing", "Marketing",
      "Testing whether a marketing channel or tactic actually causes conversions or just captures them.",
      "Classic method: geo holdout. Some conversions would happen anyway; incrementality measures the real lift.",
      ["attribution", "mer"]),
    T("mmm", "Marketing Mix Modeling", "Marketing",
      "Statistical modeling of total marketing spend vs total revenue to estimate each channel's contribution.",
      "Privacy-safe alternative to user-level attribution. Requires scale and time-series data.",
      ["attribution", "incrementality"]),
    T("lookalike", "Lookalike Audience", "Marketing",
      "An audience the ad platform builds to resemble your existing customers based on a 'seed' list.",
      "Most useful with high-quality seed (recent customers, not full list). 1-3% are tightest, 4-10% broader.",
      ["audience-targeting"]),
    T("retargeting", "Retargeting", "Marketing",
      "Showing ads to people who've previously interacted with your brand (visited site, watched video, etc.).",
      "Cheaper than prospecting. Lower incrementality than platforms report.",
      ["prospecting", "lookalike"]),
    T("prospecting", "Prospecting", "Marketing",
      "Paid advertising aimed at new audiences who haven't engaged with the brand.",
      "Opposite of retargeting. Usually 70-85% of budget in DTC.",
      ["retargeting"]),
    T("funnel", "Funnel", "Marketing",
      "The conceptual journey from first touch to paying customer, stages narrowing like a funnel.",
      "Top: awareness. Middle: consideration. Bottom: conversion. Tools and tactics differ by stage.",
      ["awareness", "conversion"]),
    T("conversion", "Conversion", "Marketing",
      "A desired action completed by a visitor: signup, purchase, demo request, form fill.",
      "Different campaigns optimize for different conversions. The event must be trackable to optimize for it.",
      ["cpa", "cac"]),
    T("conversion-rate", "Conversion Rate", "Marketing",
      "Percentage of visitors who complete a conversion.",
      "Typical ranges: 2-5% for ecommerce landing pages, 10-20% for lead gen landing pages.",
      ["cro", "conversion"]),
    T("cro", "CRO", "Marketing",
      "Conversion Rate Optimization. The practice of improving the % of visitors who convert.",
      "Typical activities: A/B testing, UX improvements, copy refinement, form optimization.",
      ["conversion-rate", "ab-test"]),
    T("ab-test", "A/B Test", "Marketing",
      "Comparing two variants (A and B) to determine which performs better.",
      "Requires statistical significance. Small differences need large samples.",
      ["cro", "statistical-significance"]),
    T("icp", "ICP", "Marketing",
      "Ideal Customer Profile. Detailed definition of the customer you most want to acquire.",
      "Includes firmographics (size, industry), role, situation, pain, and signals. Tighter ICP = better-targeted marketing.",
      ["persona", "market-fit"]),
    T("persona", "Buyer Persona", "Marketing",
      "A fictionalized representation of an ICP individual: their day, worries, decisions, language.",
      "Used to make marketing more specific and on-tone.",
      ["icp"]),
    T("pmf", "Product-Market Fit", "Marketing",
      "The stage where a product reliably converts prospects to paying customers in a real market.",
      "Before PMF, paid ads amplify a weak offer. After PMF, paid ads accelerate growth.",
      ["icp"]),
    T("utm", "UTM Parameters", "Marketing",
      "URL parameters tagged onto links to track the source, medium, campaign in analytics.",
      "utm_source, utm_medium, utm_campaign, utm_content, utm_term. Essential for multi-channel tracking.",
      ["attribution"]),

    # DIRECT RESPONSE (15)
    T("direct-response", "Direct Response", "Direct Response",
      "Advertising designed to elicit a measurable immediate response (buy, click, call, reply).",
      "Opposite of brand advertising. Every ad has a specific offer, deadline, and CTA.",
      ["offer", "cta"]),
    T("offer", "Offer", "Direct Response",
      "What you're asking the prospect to do and what they get in return.",
      "Includes core product, price, guarantee, bonuses, urgency. The offer matters more than the copy.",
      ["direct-response", "value-equation"]),
    T("value-equation", "Value Equation", "Direct Response",
      "Perceived value = (dream outcome × likelihood of achievement) / (time delay × effort).",
      "Popularized by Alex Hormozi. Framework for diagnosing weak offers.",
      ["offer"]),
    T("cta", "CTA", "Direct Response",
      "Call-To-Action. The specific next step you want the reader to take.",
      "'Book a demo' is a CTA. 'Contact us' is not specific enough.",
      ["direct-response", "conversion"]),
    T("guarantee", "Guarantee", "Direct Response",
      "A promise to the buyer that reduces their risk (money-back, satisfaction, performance).",
      "Stronger guarantees increase conversion more than they increase refunds. Under-used lever.",
      ["offer"]),
    T("lead-magnet", "Lead Magnet", "Direct Response",
      "A free resource offered in exchange for contact information. The opt-in incentive.",
      "Templates, checklists, mini-courses, audits, newsletters.",
      ["lead-gen"]),
    T("lead-gen", "Lead Generation", "Direct Response",
      "The process of attracting and capturing potential customer contact info for follow-up.",
      "Core four channels: warm outreach, content, cold outreach, paid ads.",
      ["lead-magnet"]),
    T("sales-letter", "Sales Letter", "Direct Response",
      "A long-form written piece that walks the reader from problem to solution to offer.",
      "Classic direct-response format. Still used for high-ticket offers. Often now delivered as VSLs.",
      ["vsl", "copywriting"]),
    T("vsl", "VSL", "Direct Response",
      "Video Sales Letter. Long-form video that pitches a single offer, structured like a classic sales letter.",
      "15-60 minutes typical. Still dominant format for high-ticket courses, coaching, info products.",
      ["sales-letter", "copywriting"]),
    T("copywriting", "Copywriting", "Direct Response",
      "The craft of writing words designed to persuade a reader to take an action.",
      "Different from content writing. Direct response copywriting is the highest-leverage subset.",
      ["direct-response", "headlines"]),
    T("headlines", "Headlines", "Direct Response",
      "The first line of a piece of copy. The gate that decides if the reader continues.",
      "Halbert: '80% of the success of an ad is in the headline.'",
      ["copywriting", "hooks"]),
    T("hooks", "Hooks", "Direct Response",
      "The opening line or moment that stops scroll / earns attention.",
      "On video: the first 3 seconds. On text: the first sentence.",
      ["headlines", "copywriting"]),
    T("urgency", "Urgency", "Direct Response",
      "Time-based reason to act now. Cohort closing, price rising, bonus expiring.",
      "Real urgency works. Fake urgency (countdown timer that resets) destroys trust.",
      ["scarcity", "offer"]),
    T("scarcity", "Scarcity", "Direct Response",
      "Quantity-based reason to act now. Limited seats, limited stock, limited capacity.",
      "Real scarcity works. Manufactured scarcity gets caught.",
      ["urgency", "offer"]),
    T("pas", "PAS", "Direct Response",
      "Problem-Agitate-Solution. Classical copywriting formula. Name the problem, make it vivid, present the solution.",
      "Kennedy's favorite. Works for email, blog intros, sales letters.",
      ["aida", "pastor", "copywriting"]),
    T("aida", "AIDA", "Direct Response",
      "Attention-Interest-Desire-Action. The oldest copywriting formula (1898).",
      "Works for short-form direct response. Each element does one job.",
      ["pas", "copywriting"]),
    T("pastor", "PASTOR", "Direct Response",
      "Problem-Amplify-Story-Transformation-Offer-Response. Expanded formula for long-form.",
      "Useful for VSLs, sales letters, long launch emails.",
      ["pas", "vsl"]),

    # SEO (15)
    T("seo", "SEO", "SEO",
      "Search Engine Optimization. The practice of improving a site's visibility in organic search results.",
      "Includes on-page (content, meta tags), technical (speed, crawlability), and off-page (backlinks).",
      ["serp", "backlink", "ranking"]),
    T("serp", "SERP", "SEO",
      "Search Engine Results Page. The page Google shows for a query.",
      "Modern SERPs include ads, featured snippets, map packs, knowledge panels, not just organic links.",
      ["seo"]),
    T("backlink", "Backlink", "SEO",
      "A link from another website to yours. A key ranking signal.",
      "Quality matters more than quantity. One link from a DR 60+ site often beats 100 low-quality links.",
      ["seo", "domain-rating"]),
    T("domain-rating", "Domain Rating / Authority", "SEO",
      "Scores (Ahrefs DR, Moz DA) estimating a site's authority based on backlink profile.",
      "Range 0-100. Correlates with ranking potential but not a Google metric.",
      ["backlink", "seo"]),
    T("keyword", "Keyword", "SEO",
      "A word or phrase users type into search engines.",
      "SEO strategy revolves around targeting the right keywords at appropriate difficulty.",
      ["search-volume", "keyword-difficulty"]),
    T("search-volume", "Search Volume", "SEO",
      "Estimated number of monthly searches for a keyword.",
      "Tools estimate this. Higher volume = more traffic potential but also more competition.",
      ["keyword", "keyword-difficulty"]),
    T("keyword-difficulty", "Keyword Difficulty", "SEO",
      "Estimate of how hard it is to rank for a keyword. Based on competing sites' authority.",
      "Low-KD keywords are the fastest wins for new sites.",
      ["keyword", "seo"]),
    T("on-page-seo", "On-Page SEO", "SEO",
      "Optimizations on the page itself: title, meta description, headings, content, internal links.",
      "What you can directly control. The foundation of SEO.",
      ["seo", "meta-description"]),
    T("meta-description", "Meta Description", "SEO",
      "The text snippet shown under your page title in search results.",
      "140-160 chars. Doesn't directly affect ranking but affects CTR, which can affect ranking indirectly.",
      ["on-page-seo", "serp"]),
    T("technical-seo", "Technical SEO", "SEO",
      "Site-level optimizations: crawlability, speed, mobile-friendliness, structured data, redirects.",
      "Foundation that makes on-page and off-page SEO work.",
      ["seo"]),
    T("schema", "Schema Markup", "SEO",
      "Structured data that tells search engines what your content is about (article, product, event, FAQ).",
      "Can result in rich results (star ratings, FAQ dropdowns, etc.).",
      ["technical-seo"]),
    T("ranking", "Ranking", "SEO",
      "Position on the SERP. Rank 1 gets the most clicks; rank 10 gets very few.",
      "Position 1 gets ~30% of clicks; position 10 gets ~2%.",
      ["seo", "serp"]),
    T("featured-snippet", "Featured Snippet", "SEO",
      "A special SERP result that answers a query directly from your content, placed above normal rank-1.",
      "Position 0. Requires structured, direct-answer content.",
      ["serp"]),
    T("content-cluster", "Content Cluster", "SEO",
      "A pillar page + supporting pages on a topic, all interlinked to build topical authority.",
      "Modern SEO strategy for ranking across related keywords.",
      ["seo"]),
    T("local-seo", "Local SEO", "SEO",
      "Optimization for location-based searches ('dentist near me'). Focuses on Google Business Profile, local citations, reviews.",
      "Huge for service businesses in specific geographies.",
      ["seo", "google-business-profile"]),
    T("google-business-profile", "Google Business Profile", "SEO",
      "Free business listing on Google, shows in Maps and local search.",
      "Foundation of local SEO. Was called Google My Business.",
      ["local-seo"]),

    # SALES (10)
    T("sdr", "SDR", "Sales",
      "Sales Development Representative. The prospecting role in B2B sales teams.",
      "Books meetings. Usually owns email, LinkedIn, cold calls. Hands off to AEs.",
      ["ae", "outbound"]),
    T("ae", "AE", "Sales",
      "Account Executive. The closer role in B2B sales.",
      "Takes qualified meetings, runs the sales process, closes.",
      ["sdr", "quota"]),
    T("quota", "Quota", "Sales",
      "Revenue target assigned to a sales rep for a time period.",
      "Typical: 4-5x OTE for AEs in B2B SaaS.",
      ["ote", "ae"]),
    T("ote", "OTE", "Sales",
      "On-Target Earnings. Total compensation (base + variable) if quota is met.",
      "Standard way to express sales comp.",
      ["quota"]),
    T("pipeline", "Pipeline", "Sales",
      "Active sales opportunities at various stages, tracked in a CRM.",
      "Pipeline coverage of 3x quota is healthy.",
      ["forecast", "quota"]),
    T("forecast", "Forecast", "Sales",
      "Prediction of what will close in a period. Usually Commit, Best Case, Pipeline, Omitted categories.",
      "Accuracy improves with discipline and historical data.",
      ["pipeline"]),
    T("outbound", "Outbound", "Sales",
      "Sales activity where you initiate contact with prospects (cold email, calls, LinkedIn).",
      "Opposite of inbound (leads coming to you).",
      ["inbound", "sdr"]),
    T("inbound", "Inbound", "Sales",
      "Leads that come to you (via content, ads, referrals).",
      "Typically higher intent than outbound but less control over volume.",
      ["outbound"]),
    T("discovery-call", "Discovery Call", "Sales",
      "The first substantive sales conversation. Goal: qualify the prospect, understand their situation.",
      "Usually 30-45 minutes. Not a pitch - a diagnostic.",
      ["ae"]),
    T("meddic", "MEDDIC", "Sales",
      "Qualification framework. Metrics, Economic Buyer, Decision Criteria, Decision Process, Identify Pain, Champion.",
      "Adopted for complex B2B sales. MEDDPICC adds Paper Process and Competition.",
      ["discovery-call"]),

    # BUSINESS / OPS (10)
    T("arr", "ARR", "Business",
      "Annual Recurring Revenue. Contracted subscription revenue on an annualized basis.",
      "SaaS standard. Monthly subscriptions × 12.",
      ["mrr", "saas"]),
    T("mrr", "MRR", "Business",
      "Monthly Recurring Revenue. ARR / 12. Useful for month-over-month growth tracking.",
      "",
      ["arr"]),
    T("churn", "Churn", "Business",
      "Customers or revenue lost in a period. Monthly churn = cancellations / total customers.",
      "Gross churn is cancellations. Net churn accounts for upsell offsets (can be negative - good).",
      ["nrr", "retention"]),
    T("nrr", "NRR", "Business",
      "Net Revenue Retention. Revenue from existing customers this period ÷ their revenue last period.",
      ">100% means you're growing revenue from existing customers faster than churn. Elite SaaS is 120%+.",
      ["churn", "expansion"]),
    T("retention", "Retention", "Business",
      "The percentage of customers still active after a time period.",
      "Cohort retention shows this by month-of-signup.",
      ["churn"]),
    T("kpi", "KPI", "Business",
      "Key Performance Indicator. A metric linked to a specific business goal.",
      "Should be actionable, measurable, and tied to outcomes.",
      ["okr"]),
    T("okr", "OKR", "Business",
      "Objectives and Key Results. Goal-setting framework: one qualitative objective, 2-4 measurable key results.",
      "Popularized by Google. Works when treated as priority-setting, not performance management.",
      ["kpi"]),
    T("runway", "Runway", "Business",
      "How many months a company can operate at current burn rate before running out of cash.",
      "Cash ÷ monthly burn. Critical for pre-profitable companies.",
      ["burn-rate"]),
    T("burn-rate", "Burn Rate", "Business",
      "Monthly cash loss (gross burn) or net cash decrease (net burn).",
      "For startups, the most important operational number after revenue.",
      ["runway"]),
    T("p-and-l", "P&L", "Business",
      "Profit and Loss statement. Revenue - COGS - OpEx = Net Income.",
      "One of the three core financial statements. Every operator should be able to read one.",
      ["gross-margin", "opex"]),
]


if __name__ == "__main__":
    build_glossary(TERMS)
